// AUTO-GENERATED by scripts/generate-sitemap-dates.mjs — DO NOT EDIT BY HAND.
// Regenerated on every deploy from git history (see .github/workflows/deploy.yml).
// Feeds the sitemap <lastmod>: deploys that do not change a section's content
// no longer refresh that section's lastmod (Google ignores gamed lastmod values).
export const SITEMAP_DATES: Record<string, string> = {
  "home": "2026-09-26T06:11:59Z",
  "tools": "2026-09-26T06:11:59Z",
  "pokedex": "2026-09-26T08:29:05Z",
  "generations": "2026-08-30T05:16:17Z",
  "types": "2026-08-30T05:16:17Z",
  "moves": "2026-09-26T08:29:05Z",
  "abilities": "2026-09-26T08:29:05Z",
  "blog": "2026-09-11T04:31:04Z",
  "info": "2026-09-26T06:11:59Z"
};
